name: CI Pipeline + ArgoCD

on:
    push:
        branches:
            - main
        paths-ignore:
            - 'README.md'
            - 'helm/**'
            - 'k8s/**'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v5
            - name: Setup NodeJS
              uses: actions/setup-node@v5
              with:
                node-version: '20'
            - name: Installing Frontend Dependencies
              working-directory: ./Ui
              run: |
                npm install
            - name: Installing Backend Dependencies
              working-directory: ./server
              run: |
                npm install
    
    Code-Scan:
        needs: build
        runs-on: ubuntu-latest
        permissions:
            actions: read
            contents: read
            security-events: write
        steps:
           - name: Checkout code
             uses: actions/checkout@v5
           - name: Initialize CodeQL
             uses: github/codeql-action/init@v3
             with:
               languages: javascript
           - name: Run CodeQL Analysis
             uses: github/codeql-action/analyze@v3.28.19

    docker_build_and_push:
        needs: [build, Code-Scan]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v5
            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Log in to DockerHub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and Push Frontend Image
              uses: docker/build-push-action@v6
              with:
                context: ./Ui
                file: ./Ui/Dockerfile
                push: true
                tags: ${{ secrets.DOCKER_USERNAME }}/mern-sample-app-frontend:${{ github.run_id }}
            
            - name: Build and Push Backend Image
              uses: docker/build-push-action@v6
              with:
                context: ./server
                file: ./server/Dockerfile
                push: true
                tags: ${{ secrets.DOCKER_USERNAME }}/mern-sample-app-backend:${{ github.run_id }}
        
    updating_latest_tag-in-helm-chart:
            needs: docker_build_and_push
            runs-on: ubuntu-latest
            permissions:
                contents: write
            steps:
                - name: Checkout code
                  uses: actions/checkout@v5
                  with:
                    token: ${{ secrets.TOKEN_GIT }}
                - name: Update Helm Chart with Latest Image Tag
                  run: |
                    sed -i "s|tag: .*|tag: ${{ github.run_id }}|g" ./helm/mern-helm-chart/values.yaml
                - name: Commit and Push Changes
                  run: |
                    git config --global user.name 'Shikhrshukla'
                    git config --global user.email 'shikhar31690.1@gmail.com'
                    git add ./helm/mern-helm-chart/values.yaml
                    git commit -m "Update Helm Chart with latest image tags"
                    git push
